export const LOGIN_PAGE_TYPING = 'LOGIN_PAGE_TYPING';
export const SIGNUP_PAGE_TYPING = 'SIGNUP_PAGE_TYPING';
export const NEWSFEED_PAGE_TYPING = 'NEWSFEED_PAGE_TYPING';

export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const AUTHENTICATION_ABORTED = 'AUTHENTICATION_ABORTED';

export const REGISTERING_USER = 'SIGNUP_PAGE_SUBMIT';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const REGISTRATION_ABORTED = 'REGISTRATION_ABORTED';

export const POSTING_CONTENT = 'POSTING_CONTENT';
export const POSTING_SUCCESS = 'POSTING_SUCCESS';
export const POSTING_FAILURE = 'POSTING_FAILURE';
export const POSTING_ABORTED = 'POSTING_ABORTED';
export const CONTENT_TO_POST_EMPTY = 'CONTENT_TO_POST_EMPTY';


export const FETCHING_INITIAL_POSTS = 'FETCHING_INITIAL_POSTS';
export const INITIAL_POSTS_SUCCESS = 'INITIAL_POSTS_SUCCESS';
export const INITIAL_POSTS_FAILURE = 'INITIAL_POSTS_FAILURE';
export const INITIAL_POSTS_ABORTED = 'INITIAL_POSTS_ABORTED';

export const FETCHING_RECENT_POSTS = 'FETCHING_RECENT_POSTS';
export const RECENT_POSTS_SUCCESS = 'RECENT_POSTS_SUCCESS';
export const RECENT_POSTS_FAILURE = 'RECENT_POSTS_FAILURE';
export const RECENT_POSTS_ABORTED = 'RECENT_POSTS_ABORTED';

export const REVEAL_COLLECTED_POSTS = 'REVEAL_COLLECTED_POSTS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

